services:
  postgres:
    image: postgres:latest
    container_name: root-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: FrJroot
      POSTGRES_DB: mvcproject
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: FrJ@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: FrJroot
    ports:
      - "5050:80"
    depends_on:
      - postgres
  php:
    build:
      context: ./php
      dockerfile: DockerFile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "81:80"
    depends_on:
      - postgres
volumes:
  postgres-data: